name: reverse-proxy

services:
  reverse-proxy-app:
    build:
      context: .
      dockerfile: DockerFile.dev
    command: npm run start
    ports:
      - "8080:8080"
      - "80:80"
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: